### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by Hummer0369** [Hammer0369/furima-36243#22]
# URL
https://furima-36243.herokuapp.com/

# Basic認証
ユーザー名：admin
パスワード：2222

# 出品者用アカウント
メールアドレス：example@example.com
パスワード：123abc

# 購入者用アカウント
メールアドレス：example@example.jp
パスワード：123abc

**Comment by takumi0530** [comment]
@Hammer0369 さん、お待たせいたしました。ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
これからもスタッフ一同応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像2](https://user-images.githubusercontent.com/76197191/129502014-dbd34109-21c0-4ffc-b555-b01f939d26e0.png)
